### PR TITLE
Fix run mode specific folder name

### PR DESCRIPTION
**Pull request by kwin**

### CODE REVIEW

**Review by davidjgonzalez — APPROVED** [review]

**Comment by bohnertchris** [comment]
Thanks for catching this, @kwin. We will correct it.

CQDOC-20213

**Comment by bohnertchris** [comment]
This was corrected with commit 65c8f73.

**Comment by kwin** [comment]
@bohnertchris Please keep the original author commit information (potentially leveraging co-author metadata like outlined in https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors#creating-co-authored-commits-on-the-command-line).

**Comment by bohnertchris** [comment]
I was not aware of this feature or the need. Thank you for pointing this out, @kwin. I have updated our internal procedure and shared this with our team of triagers.

**Pull request closed without merging**
