### PR TITLE
AzCopy does not support windows servers or laptops

### PR DESCRIPTION
**Pull request by pat-lego**
Please see https://jira.corp.adobe.com/browse/CQ-4351974

### CODE REVIEW

**Comment by atopper** [comment]
Many people use the acronym "CTT" for the whole process, and not just for extraction.  Can this be changed to something like "CTT's extraction does not currently..." so people do not get confused with Ingestions?  (Yes - for Ingestions "Windows" doesn't really make sense, but I've seen people confused by less.)

**Comment by pat-lego** [comment]
@atopper added the recommendation

**Review by aditidc — COMMENTED** [review]
@pat-lego Please update to the following: Pre-copy using AzCopy is currently not supported on Windows during CTT extraction.

**Review by aditidc — APPROVED** [review]

**Comment by aditidc** [comment]
@sarchiz can you please publish this change? Thanks.

**Comment by aheim0** [comment]
Thanks for raising this - we will investigate.

**Comment by aheim0** [comment]
Tracked with CQDOC-20082

**Comment by aheim0** [comment]
The update has been applied directly and will be published soon.
Closing this PR.

**Pull request closed without merging**
