### PR TITLE
Update using-best-practices-analyzer.md

### PR DESCRIPTION
**Pull request by RedCat19**
Changed for clarity that BPA should be run on Stage environment (not on Author as the documentation currently states which implies Production).

### CODE REVIEW

**Comment by guillaumecarlino** [comment]
Thanks for reporting, we will review.

**Comment by guillaumecarlino** [comment]
Tracked with CQDOC-21997.

**Comment by aditidc** [comment]
@guillaumecarlino , I've reviewed it and I approve it. Please merge. Thanks.

**Comment by guillaumecarlino** [comment]
Thanks, your changes have been applied (to the source repo). They will be published soon.

**Pull request closed without merging**
