### PR TITLE
rephrased first phrase to mention Lighthouse

### PR DESCRIPTION
**Pull request by raducotescu**

### CODE REVIEW

**Comment by aheim0** [comment]
Thanks for raising this. We will integrate the changes.

**Comment by aheim0** [comment]
Tracked with CQDOC-16780.

**Comment by jyotikas** [comment]
@raducotescu, thank you for reporting.
The changes are now reflected on the page:
https://docs.adobe.com/content/help/en/experience-manager-cloud-service/implementing/using-cloud-manager/test-results/experience-audit-testing.html

**Comment by raducotescu** [comment]
🙏

**Pull request closed without merging**
