### PR TITLE
Update developer-reference-material-apis.md - add aem-upload.sh shell…

### PR DESCRIPTION
**Pull request by rwunsch**
… script

The description on how to upload to AEM Cloud Service is extensive - but still hard to understand, and are missing an example.

I create an upload shell-script , which serves as such an example, which I added to the page.

to validate - please review: https://adobe.ly/3SJNgQh .

### CODE REVIEW

**Comment by rwunsch** [comment]
to validate - please review: https://adobe.ly/3SJNgQh .

**Comment by anujkapo** [comment]
Thanks, @rwunsch. We will take a look.

**Comment by anujkapo** [comment]
Tracked with CQDOC-21033

**Comment by guillaumecarlino** [comment]
Closing to align with CQDOC-21033 which was closed

**Pull request closed without merging**
